config:
  send_anonymous_usage_stats: False

dbt_test:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER')}}"
      pass: "{{ env_var('POSTGRES_PASSWORD')}}"
      dbname: "{{ env_var('POSTGRES_DB')}}"
      schema: "{{ env_var('POSTGRES_SCHEMA')}}"